export const DATE_FORMAT = 'YYYY-MM-DD HH:mm:ss';
export const DATE_FULL_FORMAT = 'YYYY-MM-DD';
export const DATE_MOMENT_FORMAT = 'll';
export const MONTH_MOMENT_FORMAT = 'M';
export const TIME_FORMAT = 'HH:mm';
export const TIME_PM_FORMAT = 'LT';
export const DATE_PM_FORMAT = 'LL'
export const LIKE = 'like';
export const DISLIKE = 'dislike';
